### ISSUE TITLE
Improve network functions

### ISSUE THREAD

**Issue by nickjcroucher** [bacpop/PopPUNK#331]
Three issues identified:

- [ ] Enable fast pruning with cugraph networks (#322)
- [ ] Check on the ordering of names in `reflist` in the `prune_graph` function in `network.py` (#328)
- [ ] Change the network interface to be (#328):
```
G = open_network(prefix)
pruned_G = prune_graph(keep)
save_network(pruned_G)
```
